baseURL = "https://jawabase.com"
languageCode = "en-us"
title = "JawaBase"
theme = "hugo-profile"
enableRobotsTXT = true

[pagination]
pagerSize = 3

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog posts"
url = "/blogs"
weight = 1

[[Menus.main]]
identifier = "gallery"
name = "Gallery"
title = "Blog posts"
url = "/gallery"
weight = 2

[params]
title = "JawaBase"
description = "A Leading Digital Transformator for Your Business Productivity"
favicon = "/fav.png"
useBootstrapCDN = false
mathjax = false
animate = true

  [params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

  [params.navbar]
  align = "ms-auto"
  brandName = "JawaBase"
  disableSearch = false
  enableSeparator = false

    [params.navbar.stickyNavBar]
    enable = true
    showOnScrollUp = true

    [params.navbar.menus]
    disableAbout = false
    disableExperience = true
    disableEducation = true
    disableProjects = false
    disableAchievements = false
    disableContact = false

  [params.hero]
  enable = true
  intro = "Hi, we are"
  title = "JawaBase"
  subtitle = "Enhance Productivity Through Digital Transformation"
  content = "At JawaBase, we specialize in digital transformation solutions that enhance business productivity and efficiency. Harnessing AI power, we create customized solution to significantly increase your business productivity"
  image = "/images/phone.png"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/JawaBase"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-x-twitter"
url = "https://x.com/jawabase"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-threads"
url = "https://threads.com/@jawabase"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-instagram"
url = "https://instagram.com/jawabase"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-linkedin"
url = "https://linkedin.com/company/jawabase"

  [params.about]
  enable = true
  title = "About Us"
  image = "/fav.png"
  content = """
At JawaBase, we are committed to empowering businesses through technology. As a leading digital transformator, we help companies enhance productivity, streamline operations, and scale efficiently with custom software development, system integration, and IT consulting.

Our Expertise\n
🔹 AI-Powered Solutions – Integrating AI into technical systems for smarter automation and decision-making\n
🔹 Frontend Development – Building modern, high-performance interfaces using Vue.js, React, and Next.js\n
🔹 Backend Development – Creating secure, scalable backends with PHP, Ruby on Rails, Node.js, and Golang\n
🔹 Enterprise & Cloud Solutions – Custom business applications and cloud-based infrastructures\n
🔹 System Integration – Ensuring seamless connectivity between digital tools and platforms\n

With a focus on innovation, agility, and long-term partnerships, JawaBase is your trusted IT agency for driving digital transformation and maximizing business potential.

🚀 Let’s build the future of your business together!"""

  [params.achievements]
  enable = true

    [[params.achievements.items]]
    title = "Google kickstart runner"
    content = "I solved all problems with optimal solution."
    url = "https://example.com"
    image = "/images/achievment.jpg"

    [[params.achievements.items]]
    title = "Facebook Hackathon Winner"
    content = "Developed a product using Artificial Intelligence."
    image = "/images/achievment.jpg"

    [[params.achievements.items]]
    title = "Hugo Profile"
    content = "Developed a theme and getting 1K+ downloads per month."
    url = "https://github.com/gurusabarish/hugo-profile"
    image = "/images/achievment.jpg"

    [[params.achievements.items]]
    title = "Microsoft Imagine Runner"
    content = "We are developed a product which can help others."

    [[params.achievements.items]]
    title = "Google Summer of Code"
    content = "Contributed to a open source project."
    url = "https://example.com"

  [params.projects]
  enable = true

    [[params.projects.items]]
    title = "Hugo Profile"
    content = "A highly customizable and mobile first Hugo template for personal portfolio and blog."
    image = "/images/projects/profile.png"
    badges = [ "Hugo", "Bootstrap", "Javascript" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://hugo-profile.netlify.app"

      [[params.projects.items.links]]
      icon = "fa fa-envelope"
      url = "mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/hugo-profile"

      [[params.projects.items.links]]
      icon = "fab fa-twitter"
      url = "https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile"

    [[params.projects.items]]
    title = "Image Converter"
    content = "A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django."
    image = "/images/projects/converter.jpg"
    badges = [ "Django", "Bootstrap" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://django-converter.herokuapp.com"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/converter"

    [[params.projects.items]]
    title = "Hugo Profile V2"
    content = "A clean and simple Hugo template for personal portfolio and blog."
    image = "/images/projects/profile2.jpg"
    badges = [ "Hugo", "Bootstrap", "Javascript" ]

      [params.projects.items.featured]
      name = "Demo V2"
      link = "https://hugo-profile-2.netlify.app"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/HugoProfileV2"

  [params.contact]
  enable = true
  content = "My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
  btnName = "Mail me"
  btnLink = "mailto:gurusabarisha@gmail.com"

[params.footer.recentPosts]
path = "blogs"
count = 3
title = "Recent Posts"
enable = true
disableFeaturedImage = false

[params.footer.socialNetworks]
github = "https://github.com"
linkedin = "https://linkedin.com"
x = "https://twitter.com"
instagram = "https://instagram.com"
facebook = "https://facebook.com"

  [params.listPages]
  disableFeaturedImage = false

  [params.singlePages]
  socialShare = true

    [params.singlePages.readTime]
    enable = true
    content = "min read"

    [params.singlePages.scrollprogress]
    enable = true

    [params.singlePages.tags]
    openInNewTab = true

  [params.terms]
  read = "Read"
  toc = "Table Of Contents"
  copyright = "All rights reserved"
  pageNotFound = "Page not found"
  emailText = "Check out this site"

  [params.datesFormat]
  article = "Jan 2, 2006"
  articleList = "Jan 2, 2006"
  articleRecent = "Jan 2, 2006"

