baseURL = "https://jawabase.com"
languageCode = "en-us"
title = "JawaBase - Enhance Your Productivity Through Digital Transformation"
theme = "hugo-profile"
enableRobotsTXT = true

[pagination]
pagerSize = 3

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog posts"
url = "/blogs"
weight = 1

[[Menus.main]]
identifier = "gallery"
name = "Gallery"
title = "Blog posts"
url = "/gallery"
weight = 2

[params]
title = "JawaBase"
description = "A Leading Digital Transformator for Your Business Productivity"
favicon = "/fav.png"
useBootstrapCDN = true
mathjax = false
animate = true

  [params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

  [params.navbar]
  align = "ms-auto"
  brandName = "JawaBase"
  disableSearch = false
  enableSeparator = false

    [params.navbar.stickyNavBar]
    enable = true
    showOnScrollUp = true

    [params.navbar.menus]
    disableAbout = false
    disableExperience = true
    disableEducation = true
    disableProjects = false
    disableAchievements = false
    disableContact = false

  [params.hero]
  enable = true
  intro = "Hi, we are"
  title = "JawaBase"
  subtitle = "Enhance Productivity Through Digital Transformation"
  content = "At JawaBase, we specialize in digital transformation solutions that enhance business productivity and efficiency. Harnessing AI power, we create customized solution to significantly increase your business productivity"
  image = "/images/phone.png"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/JawaBase"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-x-twitter"
url = "https://x.com/jawabase"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-threads"
url = "https://threads.com/@jawabase"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-instagram"
url = "https://instagram.com/jawabase"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-linkedin"
url = "https://linkedin.com/company/jawabase"

  [params.about]
  enable = true
  title = "About Us"
  image = "/fav.png"
  content = """
At JawaBase, we are committed to empowering businesses through technology. As a leading digital transformator, we help companies enhance productivity, streamline operations, and scale efficiently with custom software development, system integration, and IT consulting.

Our Expertise\n
🔹 AI-Powered Solutions – Integrating AI into technical systems for smarter automation and decision-making\n
🔹 Frontend Development – Building modern, high-performance interfaces using Vue.js, React, and Next.js\n
🔹 Backend Development – Creating secure, scalable backends with PHP, Ruby on Rails, Node.js, and Golang\n
🔹 Enterprise & Cloud Solutions – Custom business applications and cloud-based infrastructures\n
🔹 System Integration – Ensuring seamless connectivity between digital tools and platforms\n

With a focus on innovation, agility, and long-term partnerships, JawaBase is your trusted IT agency for driving digital transformation and maximizing business potential.

🚀 Let’s build the future of your business together!"""

  [params.achievements]
  enable = true
  title = "Our Teams"

    [[params.achievements.items]]
    title = "Ahmad Ridwan Fauzi (COO)"
    content = "8+ years of entrepreneurial experience. Software developer from heart, business developer from mind"
    image = "/images/teams/oji.jpg"

    [[params.achievements.items]]
    title = "Ahmad Mundhofa (CTO)"
    content = "7+ years of software development experience. Mastering all elements of development"
    image = "/images/teams/dhofa.jpg"

  [params.projects]
  enable = true

    [[params.projects.items]]
    title = "TeeOnMe.com - T-shirt Design Marketplace"
    content = "A marketplace for selling your own t-shirt design on a commission-based in US"
    image = "/images/projects/project-1.jpg"
    badges = [ "RoR", "React" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://teeonme.com"

    [[params.projects.items]]
    title = "Komodra - Textile Trading Company"
    content = "A website for textile trading company based in Italy. We implemented ERP for the company as well."
    image = "/images/projects/project-3.jpg"
    badges = [ "VueJS", "Frappe" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://komodra.com"

    [[params.projects.items]]
    title = "2Gaijin.com - Secondhand Marketplace for Foreigners in Japan"
    content = "A marketplace for trading secondhand items in Japan built on Go and ReactJS"
    image = "/images/projects/project-2.jpg"
    badges = [ "Go", "React" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://www.figma.com/design/C9YTkVHw2iz0poEe5mLhi4/%E2%9C%8C%EF%B8%8F2Gaijin---Secondhand-Platform-for-Gaijin?node-id=0-1&p=f&t=FaIr1oRrhNgLVyYY-0"

  [params.contact]
  enable = true
  content = "Have a project in mind or need expert IT solutions? We're here to help! Contact us today to discuss how we can transform your business with cutting-edge technology."
  btnName = "Mail us"
  btnLink = "mailto:jawa.based@gmail.com"

[params.footer.recentPosts]
path = "blogs"
count = 3
title = "Recent Posts"
enable = true
disableFeaturedImage = false

[params.footer.socialNetworks]
github = "https://github.com/JawaBase"
linkedin = "https://linkedin.com/company/jawabase"
x = "https://x.com/jawabase"
instagram = "https://instagram.com/jawabase"

  [params.listPages]
  disableFeaturedImage = false

  [params.singlePages]
  socialShare = true

    [params.singlePages.readTime]
    enable = true
    content = "min read"

    [params.singlePages.scrollprogress]
    enable = true

    [params.singlePages.tags]
    openInNewTab = true

  [params.terms]
  read = "Read"
  toc = "Table Of Contents"
  copyright = "All rights reserved"
  pageNotFound = "Page not found"
  emailText = "Check out this site"

  [params.datesFormat]
  article = "Jan 2, 2006"
  articleList = "Jan 2, 2006"
  articleRecent = "Jan 2, 2006"

